<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class OccupationSeeder extends Seeder
{
    public function run(): void
    {
        $occupations = [
            ['name' => json_encode(['cn' => '软件工程师', 'en' => 'Software Engineer'])],
            ['name' => json_encode(['cn' => '医生', 'en' => 'Doctor'])],
            ['name' => json_encode(['cn' => '教师', 'en' => 'Teacher'])],
            ['name' => json_encode(['cn' => '厨师', 'en' => 'Chef'])],
            ['name' => json_encode(['cn' => '设计师', 'en' => 'Designer'])],
            ['name' => json_encode(['cn' => '市场经理', 'en' => 'Marketing Manager'])],
            ['name' => json_encode(['cn' => '销售主管', 'en' => 'Sales Executive'])],
            ['name' => json_encode(['cn' => '项目经理', 'en' => 'Project Manager'])],
            ['name' => json_encode(['cn' => '金融分析师', 'en' => 'Financial Analyst'])],
            ['name' => json_encode(['cn' => '律师', 'en' => 'Lawyer'])],
            ['name' => json_encode(['cn' => '护士', 'en' => 'Nurse'])],
            ['name' => json_encode(['cn' => '会计师', 'en' => 'Accountant'])],
            ['name' => json_encode(['cn' => '行政助理', 'en' => 'Administrative Assistant'])],
            ['name' => json_encode(['cn' => '人力资源经理', 'en' => 'HR Manager'])],
            ['name' => json_encode(['cn' => '数据分析师', 'en' => 'Data Analyst'])],
            ['name' => json_encode(['cn' => '产品经理', 'en' => 'Product Manager'])],
            ['name' => json_encode(['cn' => '平面设计师', 'en' => 'Graphic Designer'])],
            ['name' => json_encode(['cn' => '网页开发员', 'en' => 'Web Developer'])],
            ['name' => json_encode(['cn' => '建筑师', 'en' => 'Architect'])],
            ['name' => json_encode(['cn' => '机师', 'en' => 'Pilot'])],
            ['name' => json_encode(['cn' => '船长', 'en' => 'Ship Captain'])],
            ['name' => json_encode(['cn' => '银行职员', 'en' => 'Bank Officer'])],
            ['name' => json_encode(['cn' => '保险顾问', 'en' => 'Insurance Consultant'])],
            ['name' => json_encode(['cn' => '证券交易员', 'en' => 'Stock Trader'])],
            ['name' => json_encode(['cn' => '自由职业者', 'en' => 'Freelancer'])],
            ['name' => json_encode(['cn' => '摄影师', 'en' => 'Photographer'])],
            ['name' => json_encode(['cn' => '内容创作者', 'en' => 'Content Creator'])],
            ['name' => json_encode(['cn' => '电气工程师', 'en' => 'Electrical Engineer'])],
            ['name' => json_encode(['cn' => '机械工程师', 'en' => 'Mechanical Engineer'])],
            ['name' => json_encode(['cn' => '土木工程师', 'en' => 'Civil Engineer'])],
            ['name' => json_encode(['cn' => '软件开发员', 'en' => 'Software Developer'])],
            ['name' => json_encode(['cn' => '系统分析师', 'en' => 'Systems Analyst'])],
            ['name' => json_encode(['cn' => '药剂师', 'en' => 'Pharmacist'])],
            ['name' => json_encode(['cn' => '牙医', 'en' => 'Dentist'])],
            ['name' => json_encode(['cn' => '心理学家', 'en' => 'Psychologist'])],
            ['name' => json_encode(['cn' => '咨询师', 'en' => 'Consultant'])],
            ['name' => json_encode(['cn' => '企业家', 'en' => 'Entrepreneur'])],
            ['name' => json_encode(['cn' => '首席执行官', 'en' => 'CEO'])],
            ['name' => json_encode(['cn' => '首席财务官', 'en' => 'CFO'])],
            ['name' => json_encode(['cn' => '公务员', 'en' => 'Civil Servant'])],
            ['name' => json_encode(['cn' => '行政人员', 'en' => 'Administrator'])],
            ['name' => json_encode(['cn' => '采购主管', 'en' => 'Purchasing Manager'])],
            ['name' => json_encode(['cn' => '物流专员', 'en' => 'Logistics Officer'])],
            ['name' => json_encode(['cn' => '仓库管理员', 'en' => 'Warehouse Manager'])],
            ['name' => json_encode(['cn' => '活动策划', 'en' => 'Event Planner'])],
            ['name' => json_encode(['cn' => '新闻记者', 'en' => 'Journalist'])],
            ['name' => json_encode(['cn' => '作家', 'en' => 'Writer'])],
            ['name' => json_encode(['cn' => '编辑', 'en' => 'Editor'])],
            ['name' => json_encode(['cn' => '翻译员', 'en' => 'Translator'])],
            ['name' => json_encode(['cn' => '音乐家', 'en' => 'Musician'])],
            ['name' => json_encode(['cn' => '演员', 'en' => 'Actor'])],
            ['name' => json_encode(['cn' => '模特', 'en' => 'Model'])],
            ['name' => json_encode(['cn' => '健身教练', 'en' => 'Fitness Trainer'])],
            ['name' => json_encode(['cn' => '保安', 'en' => 'Security Guard'])],
            ['name' => json_encode(['cn' => '消防员', 'en' => 'Firefighter'])],
            ['name' => json_encode(['cn' => '警察', 'en' => 'Police Officer'])],
            ['name' => json_encode(['cn' => '农民', 'en' => 'Farmer'])],
            ['name' => json_encode(['cn' => '渔夫', 'en' => 'Fisherman'])],
            ['name' => json_encode(['cn' => '司机', 'en' => 'Driver'])],
            ['name' => json_encode(['cn' => '巴士司机', 'en' => 'Bus Driver'])],
            ['name' => json_encode(['cn' => '计程车司机', 'en' => 'Taxi Driver'])],
            ['name' => json_encode(['cn' => '机械技工', 'en' => 'Mechanic'])],
            ['name' => json_encode(['cn' => '电工', 'en' => 'Electrician'])],
            ['name' => json_encode(['cn' => '水管工', 'en' => 'Plumber'])],
            ['name' => json_encode(['cn' => '木匠', 'en' => 'Carpenter'])],
            ['name' => json_encode(['cn' => '泥水匠', 'en' => 'Mason'])],
            ['name' => json_encode(['cn' => '油漆工', 'en' => 'Painter'])],
            ['name' => json_encode(['cn' => '维修员', 'en' => 'Technician'])],
            ['name' => json_encode(['cn' => '服务员', 'en' => 'Waiter'])],
            ['name' => json_encode(['cn' => '厨师助手', 'en' => 'Kitchen Assistant'])],
            ['name' => json_encode(['cn' => '收银员', 'en' => 'Cashier'])],
            ['name' => json_encode(['cn' => '商店助理', 'en' => 'Shop Assistant'])],
            ['name' => json_encode(['cn' => '清洁工', 'en' => 'Cleaner'])],
            ['name' => json_encode(['cn' => '护工', 'en' => 'Caregiver'])],
            ['name' => json_encode(['cn' => '保姆', 'en' => 'Nanny'])],
            ['name' => json_encode(['cn' => '园丁', 'en' => 'Gardener'])],
            ['name' => json_encode(['cn' => '邮差', 'en' => 'Postman'])],
            ['name' => json_encode(['cn' => '客服专员', 'en' => 'Customer Service Officer'])],
            ['name' => json_encode(['cn' => '电话销售员', 'en' => 'Telemarketer'])],
            ['name' => json_encode(['cn' => '导游', 'en' => 'Tour Guide'])],
            ['name' => json_encode(['cn' => '超市主管', 'en' => 'Supermarket Supervisor'])],
            ['name' => json_encode(['cn' => '美容师', 'en' => 'Beautician'])],
            ['name' => json_encode(['cn' => '理发师', 'en' => 'Hairdresser'])],
            ['name' => json_encode(['cn' => '按摩师', 'en' => 'Masseur'])],
            ['name' => json_encode(['cn' => '售货员', 'en' => 'Sales Assistant'])],
            ['name' => json_encode(['cn' => '房地产经纪人', 'en' => 'Property Agent'])],
            ['name' => json_encode(['cn' => '室内设计师', 'en' => 'Interior Designer'])],
            ['name' => json_encode(['cn' => '图书管理员', 'en' => 'Librarian'])],
            ['name' => json_encode(['cn' => '会展策划', 'en' => 'Exhibition Planner'])],
        ];

        DB::table('occupations')->insert($occupations);
    }
}
